In [1]:
import numpy as np
from gurobipy import Model, GRB


In [3]:

custos = np.array([
    [10, 2, 20, 11],  
    [12, 7, 9, 20],  
    [4, 14, 16, 18]   
])

oferta = [15, 25, 10]       
demanda = [5, 15, 15, 15]    

n_fabricas = len(oferta)
n_depositos = len(demanda)

m = Model()

x = m.addVars(n_fabricas, n_depositos, vtype=GRB.CONTINUOUS, name="x")

m.setObjective(
    sum(custos[i][j] * x[i, j] for i in range(n_fabricas) for j in range(n_depositos)),
    GRB.MINIMIZE
)

for i in range(n_fabricas):
    m.addConstr(sum(x[i, j] for j in range(n_depositos)) == oferta[i])

for j in range(n_depositos):
    m.addConstr(sum(x[i, j] for i in range(n_fabricas)) == demanda[j])

m.optimize()


print(f"Custo mínimo total: ${m.objVal:.2f}\n")
matriz_resultado = np.zeros((n_fabricas, n_depositos), dtype=int)

for i in range(n_fabricas):
    total_i = 0
    for j in range(n_depositos):
        val = int(round(x[i, j].X))
        matriz_resultado[i, j] = val
        if val > 0:
            print(f"Enviar {val} carretas do Silo {i+1} para o moinho {j+1}")
            total_i += val

print(matriz_resultado)


Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (win64 - Windows 11.0 (22631.2))

CPU model: AMD Ryzen 7 5700U with Radeon Graphics, instruction set [SSE2|AVX|AVX2]
Thread count: 8 physical cores, 16 logical processors, using up to 16 threads



Optimize a model with 7 rows, 12 columns and 24 nonzeros
Model fingerprint: 0x6dd56fba
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [2e+00, 2e+01]
  Bounds range     [0e+00, 0e+00]
  RHS range        [5e+00, 3e+01]
Presolve time: 0.01s
Presolved: 7 rows, 12 columns, 24 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    3.5000000e+02   3.000000e+01   0.000000e+00      0s
       2    4.3500000e+02   0.000000e+00   0.000000e+00      0s

Solved in 2 iterations and 0.02 seconds (0.00 work units)
Optimal objective  4.350000000e+02
Custo mínimo total: $435.00

Enviar 5 carretas do Silo 1 para o moinho 2
Enviar 10 carretas do Silo 1 para o moinho 4
Enviar 10 carretas do Silo 2 para o moinho 2
Enviar 15 carretas do Silo 2 para o moinho 3
Enviar 5 carretas do Silo 3 para o moinho 1
Enviar 5 carretas do Silo 3 para o moinho 4
[[ 0  5  0 10]
 [ 0 10 15  0]
 [ 5  0  0  5]]
